### ISSUE TITLE
lodash dependency

### ISSUE THREAD

**Issue by GertSallaerts** [bubobox/concat-js#1]
Two things:
1. In [package.json:30](https://github.com/bubobox/concat-js/blob/be839f3dbdedeedb9399f433c80b073b3a6dcc59/package.json#L30), `lodash` is listed as a devDependency, but the library itself uses it [here](https://github.com/bubobox/concat-js/blob/be839f3dbdedeedb9399f433c80b073b3a6dcc59/src/index.js#L27-L28). So I think it should be listed as a regular dependency.
2. ~~The project is super small and `lodash` is huge in comparison, especially since we only use two functions. On the one hand, we will probably never use this library in a project that does not use `lodash`, but on the other hand, this is a public repo so maybe we should aim for smaller size and swap the `lodash` functions out with our own?~~ [irrelevant]

**Comment by Sitebase** [comment]
1. It's indeed better to define it as regular dependency because if you for example would use it in a node application.
2. Like you said, lodash is used in our project where we will use this project so it's no problem in our case.

**Comment by Sitebase** [comment]
@mahammedzkhan I would already fix 1

**Comment by GertSallaerts** [comment]
Agreed, removed second part.
